apiVersion: v1
kind: Template
metadata:
  name: demo-broker
objects:

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: demo-broker
  spec:
    url: http://demo-broker.demo-broker.svc.cluster.local

- kind: Service
  apiVersion: v1
  metadata:
    name: demo-broker
    labels:
      app: demo-broker
  spec:
    selector:
      app: demo-broker
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: demo-broker
    labels:
      app: demo-broker
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: demo-broker
    template:
      metadata:
        labels:
          app: demo-broker
      spec:
        containers:
        - name: service-demo-broker
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command:
          - /opt/servicebroker/servicebroker
          args:
          - --port
          - "8080"
          - -v
          - "4"
          - --logtostderr
          - --insecure
          - --catalogPath
          - ${CATALOG_PATH}
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              scheme: HTTP
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: cheld/demobroker:latest

- description: base64 encoded SSL CA Certificate
  displayName: base64 encoded SSL CA Certificate
  name: BROKER_CA_CERT
  required: false
  value:

- description: Namespace that the starter pack is deployed to
  displayName: Namespace
  name: NAMESPACE
  value: demo-broker

- description: URL to a json formated resource that represents the catalog
  displayName: catalogPath
  name: CATALOG_PATH
  value: https://raw.githubusercontent.com/cheld/demo-broker/master/samples/catalog.json
